import { Header, Container } from "@/shared/components/shared"

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function CheckoutLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <main className="min-h-screen bg-gray-100">
            <Container>
                <Header isCheckout={true} />
                {children}
            </Container>
        </main>
    )
}
